version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - default
    environment:
      DJANGO_SETTINGS_MODULE: "rhizotron.settings.docker"
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py create_default_models && python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    networks:
      - default
    environment:
      DJANGO_SETTINGS_MODULE: "rhizotron.settings.docker"
    depends_on:
      app:
        condition: service_healthy
    command: >
      bash -c "python manage.py qcluster"
  client:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_AUTHORIZATION: "Basic c2hha29vcjpTaGFrb29yTGFiQDIwMjM="
      VITE_CSRFTOKEN: "flmMUwTYYyqFzwrYq7atPr7R7PRubwnZ6XlK6ynZQXDi5txGMjIUaaBt0XxxxFGa"
      VITE_BACKEND_URL: "http://localhost:8000" #TODO: change to app:8000 when in prod
    ports:
      - 0.0.0.0:5173:5173
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://client:5173/"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s
  mysqldb:
    restart: unless-stopped
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "passw0rd"
      MYSQL_DATABASE: dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  prometheus:
    restart: unless-stopped
    image: bitnami/prometheus:2.51.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s
    depends_on:
      app:
        condition: service_healthy
  redis:
    restart: unless-stopped
    image: redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s
  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.3.5
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - default

volumes:
  mysql:
  media:
  prometheus:
  redis:
  grafana:

networks:
  default: {}
