# Generated by Django 5.0.2 on 2025-03-19 22:46

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('dataset'), models.Model),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('resnet101', 'ResNet101'), ('resnet152', 'ResNet152'), ('resnet18', 'ResNet18'), ('resnet34', 'ResNet34'), ('unet', 'UNet'), ('resnet50', 'ResNet50')], default='unet', max_length=50)),
                ('model_weights', models.FileField(editable=False, upload_to='models/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('model'), models.Model),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(editable=False, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='processing.dataset')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('picture'), models.Model),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(editable=False, upload_to='masks/')),
                ('threshold', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('root_count', models.IntegerField(default=0)),
                ('average_root_diameter', models.FloatField(default=0)),
                ('total_root_length', models.FloatField(default=0)),
                ('total_root_area', models.FloatField(default=0)),
                ('total_root_volume', models.FloatField(default=0)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mask', to='processing.picture')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('mask'), models.Model),
        ),
    ]
