# Generated by Django 5.0.2 on 2025-04-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('unet', 'UNet'), ('resnet101', 'ResNet101'), ('resnet18', 'ResNet18'), ('resnet34', 'ResNet34'), ('resnet152', 'ResNet152'), ('resnet50', 'ResNet50')], default='unet', max_length=50),
        ),
    ]
