# Generated by Django 5.0.2 on 2024-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_mask_average_root_diameter_mask_root_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('resnet34', 'ResNet34'), ('resnet50', 'ResNet50'), ('unet', 'UNET'), ('resnet18', 'ResNet18'), ('resnet152', 'ResNet152'), ('resnet101', 'ResNet101')], default='unet', max_length=50)),
                ('model_weights', models.FileField(editable=False, upload_to='models/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
