# Generated by Django 5.0.2 on 2024-03-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_model_model_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('unet', 'UNET'), ('resnet152', 'ResNet152'), ('resnet18', 'ResNet18'), ('resnet34', 'ResNet34'), ('resnet50', 'ResNet50'), ('resnet101', 'ResNet101')], default='unet', max_length=50),
        ),
    ]
