# Generated by Django 5.0.2 on 2024-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_model_owner_model_public_alter_model_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('resnet34', 'ResNet34'), ('resnet152', 'ResNet152'), ('resnet18', 'ResNet18'), ('resnet50', 'ResNet50'), ('unet', 'UNet'), ('resnet101', 'ResNet101')], default='unet', max_length=50),
        ),
    ]
