# Generated by Django 5.0.2 on 2025-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_alter_model_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('resnet50', 'ResNet50'), ('resnet101', 'ResNet101'), ('resnet152', 'ResNet152'), ('resnet34', 'ResNet34'), ('resnet18', 'ResNet18'), ('unet', 'UNet')], default='unet', max_length=50),
        ),
    ]
